# using docker container
sudo: false

language: c

# Make sure build dependencies are installed.
install:
 - sudo apt-get update && sudo apt-get install nunit mono-gmcs cli-common-dev libgl1-mesa-dev libsdl1.2-dev libopenal-dev

before_script:
  - export QINIU_TEST_ENV="travis"

script:
 - make
 - make test
